import os


CURRENT_DIRECTORY = os.getcwd()
SCREEN_WIDTH = 1080
SCREEN_HEIGHT = 720
FPS = 60
LEFT = "LEFT"
LEFT_UP = "LEFT_UP"
UP = "UP"
RIGHT_UP = "RIGHT_UP"
RIGHT = "RIGHT"
RIGHT_DOWN = "RIGHT_DOWN"
DOWN = "DOWN"
LEFT_DOWN = "LEFT_DOWN"
SIZE_HEALTH_BAR = 150
