import os


CURRENT_DIRECTORY = os.getcwd()
SCREEN_WIDTH = 1080
SCREEN_HEIGHT = 720
FPS = 60
LEFT = "LEFT"
LEFT_UP = "LEFTUP"
UP = "UP"
RIGHT_UP = "RIGHTUP"
RIGHT = "RIGHT"
RIGHT_DOWN = "RIGHTDOWN"
DOWN = "DOWN"
LEFT_DOWN = "LEFTDOWN"
SIZE_HEALTH_BAR = 150
